import type { PlaylistPurpose, SongDraft } from '@/types'

export const sampleSongs: SongDraft[] = [
  {
    title: '稻香',
    artist: '周杰伦',
    genre: '流行',
    language: '国语',
    mood: '治愈',
    status: 'requestable',
    proficiency: 'familiar',
    tags: ['拿手歌'],
  },
  {
    title: '晴天',
    artist: '周杰伦',
    genre: '流行',
    language: '国语',
    mood: '伤感',
    status: 'requestable',
    proficiency: 'signature',
    tags: ['拿手歌'],
  },
  {
    title: '十年',
    artist: '陈奕迅',
    genre: '流行',
    language: '国语',
    mood: '伤感',
    status: 'requestable',
    proficiency: 'familiar',
    tags: [],
  },
  {
    title: 'K歌之王',
    artist: '陈奕迅',
    genre: '流行',
    language: '粤语',
    mood: '热场',
    status: 'requestable',
    proficiency: 'complete',
    tags: [],
  },
  {
    title: '小幸运',
    artist: '田馥甄',
    genre: '流行',
    language: '国语',
    mood: '甜',
    status: 'requestable',
    proficiency: 'familiar',
    tags: [],
  },
  {
    title: '后来',
    artist: '刘若英',
    genre: '流行',
    language: '国语',
    mood: '伤感',
    status: 'requestable',
    proficiency: 'signature',
    tags: ['大合唱'],
  },
  {
    title: '海阔天空',
    artist: 'Beyond',
    genre: '摇滚',
    language: '粤语',
    mood: '炸场',
    status: 'requestable',
    proficiency: 'complete',
    tags: ['大合唱'],
  },
  {
    title: '成都',
    artist: '赵雷',
    genre: '民谣',
    language: '国语',
    mood: '安静',
    status: 'requestable',
    proficiency: 'familiar',
    tags: [],
  },
  {
    title: '红豆',
    artist: '王菲',
    genre: '流行',
    language: '国语',
    mood: '安静',
    status: 'requestable',
    proficiency: 'complete',
    tags: [],
  },
  {
    title: '告白气球',
    artist: '周杰伦',
    genre: '流行',
    language: '国语',
    mood: '甜',
    status: 'practicing',
    proficiency: 'rough',
    tags: ['在学'],
  },
  {
    title: 'Love Story',
    artist: 'Taylor Swift',
    genre: '流行',
    language: '英语',
    mood: '甜',
    status: 'requestable',
    proficiency: 'complete',
    tags: [],
  },
  {
    title: 'Rolling in the Deep',
    artist: 'Adele',
    genre: '流行',
    language: '英语',
    mood: '炸场',
    status: 'paused',
    proficiency: 'rough',
    tags: ['高音吃力'],
  },
  {
    title: '青鸟',
    artist: '生物股长',
    genre: '流行',
    language: '日语',
    mood: '炸场',
    status: 'practicing',
    proficiency: 'rough',
    tags: ['在学'],
  },
  {
    title: '粉红色的回忆',
    artist: '韩宝仪',
    genre: '影视OST',
    language: '国语',
    mood: '热场',
    status: 'requestable',
    proficiency: 'familiar',
    tags: ['复古'],
  },
  {
    title: '错位时空',
    artist: '艾辰',
    genre: '古风',
    language: '国语',
    mood: '伤感',
    status: 'requestable',
    proficiency: 'complete',
    tags: [],
  },
  {
    title: '孤勇者',
    artist: '陈奕迅',
    genre: '流行',
    language: '国语',
    mood: '炸场',
    status: 'requestable',
    proficiency: 'signature',
    tags: ['大合唱'],
  },
]

export const samplePlaylistTitle = '今晚点歌单'
export const samplePlaylistSubtitle = '示例歌单 · 加载后即可编辑和导出'
export const samplePurpose: PlaylistPurpose = 'live'
export const sampleDimension = 'genre'
